// default package
// Generated 2009-9-17 14:28:02 by Hibernate Tools 3.2.4.GA
package smsmoscount;
import java.util.Date;
/**
 * CompanysMoscount generated by hbm2java
 */
public class CompanysMoscount implements java.io.Serializable {

	private long id;
	private String company;
	private String game;
	private int mosnum;
	private Date countdate;

	public CompanysMoscount() {
	}

	public CompanysMoscount(long id, String company, String game, int mosnum,
			Date countdate) {
		this.id = id;
		this.company = company;
		this.game = game;
		this.mosnum = mosnum;
		this.countdate = countdate;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getGame() {
		return this.game;
	}

	public void setGame(String game) {
		this.game = game;
	}

	public int getMosnum() {
		return this.mosnum;
	}

	public void setMosnum(int mosnum) {
		this.mosnum = mosnum;
	}

	public Date getCountdate() {
		return this.countdate;
	}

	public void setCountdate(Date countdate) {
		this.countdate = countdate;
	}

}
